# Generated by Django 3.1.4 on 2020-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('type_of_expense', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
